services:
  db:
    image: mysql:8
    container_name: db
    command: --innodb-use-native-aio=0
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - desafio02
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=adminpass
      - MYSQL_ROOT_PASSWORD=rootpass
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 5s
      timeout: 10s
      retries: 3

  app:
    image: node:20-alpine
    container_name: app
    working_dir: /usr/src/app
    entrypoint: sh -c "npm install && npm run start"
    volumes:
      - ./app:/usr/src/app
    depends_on:
      db:
        condition: service_healthy
    networks:
      - desafio02
        
  nginx:
    image: nginx:latest
    container_name: nginx
    networks:
      - desafio02
    depends_on:
      - app
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

networks:
  desafio02:
    driver: bridge